### Render all steps
GET http://localhost:3000/steps

### Render one step
GET http://localhost:3000/step/1

### Update a step
PATCH http://localhost:3000/step/4 HTTP/1.1
content-type: application/json

{
    "name": "Warm up"
}

### Create a step
POST http://localhost:3000/step HTTP/1.1
content-type: application/json

{
    "name": "Retour au calme",
    "distance": null,
    "duration": "60",
    "user_id": 1
}

### Delete one step
DELETE http://localhost:3000/step/5