### Render all workouts
GET http://localhost:3000/workouts

### Render one workout
GET http://localhost:3000/workout/2

### Update an event
PATCH http://localhost:3000/workout/2 HTTP/1.1
content-type: application/json

{
    "name": "Fractionned"
}