### Render all workouts
GET http://localhost:3000/workouts

### Render all user workouts
GET http://localhost:3000/workouts/user/1

### Render one workout
GET http://localhost:3000/workout/5

### Update a workout
PATCH http://localhost:3000/workout/3 HTTP/1.1
content-type: application/json

{
    "name": "Fractionné"
}

### Create a workout
POST http://localhost:3000/workout HTTP/1.1
content-type: application/json

{
    "name": "Ptit footing",
    "sport_id": 1,
    "date_scheduled": "2024-01-16",
    "user_id": 1,
    "hecho": "false"
}

### Delete one workout
DELETE http://localhost:3000/workout/3

### Add step to workout
PATCH http://localhost:3000/workout/3/step/add HTTP/1.1
content-type: application/json

{
    "step_id": 4
}

### Remove step from workout
PATCH http://localhost:3000/workout/3/step/remove HTTP/1.1
content-type: application/json

{
    "step_id": 4
}

### Add tag to workout
PATCH http://localhost:3000/workout/22/tag/add HTTP/1.1
content-type: application/json

{
    "tag_id": 3
}

### Remove tag from workout
PATCH http://localhost:3000/workout/22/tag/remove HTTP/1.1
content-type: application/json

{
    "tag_id": 3
}