BEGIN;

DROP TABLE IF EXISTS "user", "sport", "workout", "activity", "step", "workout_has_step";

CREATE TABLE "user" (
  "id" SERIAL PRIMARY KEY,
  "firstname" TEXT,
  "lastname" TEXT,
  "email" TEXT,
  "password" TEXT,
  "role" TEXT DEFAULT 'member',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "sport" (
  "id" SERIAL PRIMARY KEY,
  "name" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "workout" (
  "id" SERIAL PRIMARY KEY,
  "name" TEXT,
  "distance" NUMERIC,
  "duration" NUMERIC,
  "user_id" INTEGER NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "sport_id" INTEGER NOT NULL REFERENCES "sport"("id") ON DELETE CASCADE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "activity" (
  "id" SERIAL PRIMARY KEY,
  "name" TEXT,
  "hecho" BOOLEAN DEFAULT false,
  "date_scheduled" DATE,
  "date_accomplished" DATE,
  "sport_id" INTEGER REFERENCES "sport"("id") ON DELETE CASCADE,
  "workout_id" INTEGER REFERENCES "workout"("id") ON DELETE CASCADE,
  "user_id" INTEGER NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "step" (
  "id" SERIAL PRIMARY KEY,
  "name" TEXT,
  "distance" NUMERIC,
  "duration" NUMERIC,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE "workout_has_step" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "workout_id" INTEGER NOT NULL REFERENCES "workout"("id") ON DELETE CASCADE,
    "step_id" INTEGER NOT NULL REFERENCES "step"("id") ON DELETE CASCADE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMIT;